########## How To Use Docker Image ###############
##
##  Image Name: denny/aws-ecs-wordpress-study:latest
##  Git link: https://github.com/DennyZhang/aws-ecs-wordpress-study/blob/master/Dockerfile/wordpress/Dockerfile
##  Build docker image:
##      time docker build --no-cache -f Dockerfile_v2 -t denny/aws-ecs-wordpress-study:wordpress_v2 --rm=true .
##  Test image:
##      docker run -p 8080:80 --name wordpress-test -d denny/aws-ecs-wordpress-study:wordpress_v2
##################################################
# Base Docker image: https://github.com/DennyZhang/aws-ecs-wordpress-study/blob/master/Dockerfile/wordpress/Dockerfile_v1

FROM denny/aws-ecs-wordpress-study:wordpress_v1

LABEL maintainer "Denny<contact@dennyzhang.com>"

ENV WORDPRESS_DIR /var/www/blog

ENV WEB_PORT 80

USER root

RUN apt-get install -y gzip tar wget && \
    cd /tmp/ && wget -O latest.tar.gz https://wordpress.org/latest.tar.gz && \
    gzip -d latest.tar.gz && tar -xf latest.tar && \
    mkdir -p "$WORDPRESS_DIR" && cp -r wordpress/* "$WORDPRESS_DIR"/ && \
    rm -rf wordpress

WORKDIR $WORDPRESS_DIR

COPY ./docker-entrypoint.sh $WORDPRESS_DIR/docker-entrypoint.sh
COPY ./docker-healthcheck.sh $WORDPRESS_DIR/docker-healthcheck.sh
COPY ./wp-config.php $WORDPRESS_DIR/wp-config.php

COPY nginx_default.conf /etc/nginx/conf.d/default.conf

# Install wordpress plugins
ADD disable-canonical-redirection wp-content/plugins/disable-canonical-redirection

# TODO: avoid adding xmlrpc_denny.php
COPY xmlrpc_denny.php $WORDPRESS_DIR/xmlrpc_denny.php

ENTRYPOINT $WORDPRESS_DIR/docker-entrypoint.sh

HEALTHCHECK --interval=2m --timeout=3s \
            CMD $WORDPRESS_DIR/docker-healthcheck.sh || exit 1
